# Generated by Django 5.2.1 on 2025-05-26 03:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número único de la habitación (ej: 101, 201A)', max_length=10, unique=True, verbose_name='Número de Habitación')),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('matrimonial', 'Matrimonial'), ('suite', 'Suite'), ('familiar', 'Familiar'), ('presidencial', 'Presidencial')], max_length=20, verbose_name='Tipo de Habitación')),
                ('precio_por_noche', models.DecimalField(decimal_places=2, help_text='Precio en pesos colombianos', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio por Noche')),
                ('capacidad', models.PositiveIntegerField(help_text='Número máximo de huéspedes', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad')),
                ('servicios_incluidos', models.TextField(blank=True, help_text='Descripción de servicios incluidos (WiFi, TV, minibar, etc.)', verbose_name='Servicios Incluidos')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'Mantenimiento'), ('reservada', 'Reservada'), ('ocupada', 'Ocupada')], default='disponible', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la habitación', verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['numero'],
            },
        ),
    ]
